name: Run Omega Analyzer 
run-name: ${{ inputs.user }}/${{ inputs.repository }}

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'GitHub username'
        required: true

      repository:
        description: 'Github repository name'
        required: true

jobs:
  analyze:
    runs-on: self-hosted
    timeout-minutes: 180

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.user }}/${{ inputs.repository }}
          path: target

      - name: Pull docker image
        run: docker pull meme8383/omega-toolshed:latest

      - name: Run analyzer
        run: |
          docker rm -f $(docker ps -aq) || true
          rm -rf "$PWD/results"
          # Sometimes operating system's OOM killer does not do its work,
          # making the entire machine unresponsive.
          # We limit the memory usage of container to 30g here.
          docker run --rm -m 30g -v "$PWD/results":/opt/export/github/target/0 -v "$PWD/target":/opt/local_source/target meme8383/omega-toolshed:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ inputs.user }}-${{ inputs.repository }}
          path: ./results

      - name: Cleanup
        if: always()
        run: |
          docker rm -f $(docker ps -aq) || true
          rm -rf ./results
